### ISSUE TITLE
Can't post

### ISSUE THREAD

**Issue by bwyss** [henyana/jquery-comment#1]
When I try to post a new comment I get:
POST http://localhost:9000/articles/id/1/comments/input 404 (Not Found)

It would seem that a input file of some kind is required?

**Comment by henyana** [comment]
Hi bwyss,

Actualy you'll need to a create server side code which it should handled "POST http://localhost:9000/articles/id/1/comments/input". For example you can create PHP server side code "POST: http://localhost:9000/input.php" and make sure the response just right.

Just keep in mind that if you send the message from the top or root of the comment, you need to make sure your server return JSON format:

``` javascript
// REQUEST
POST: http://localhost:9000/input.php
From Data:
"parent_id": 0   // comment root or top
"text": "test comment"  // textarea input

// RESPONSE
{
   "success": true,
   "comment_id": 6,
   "parent_id": 0,   // comment root or top
   "text": "test comment",   // textarea input
   "in_reply_to": null,
   "created_by": 1,
   "posted_date": "2014-12-13 01:57:42",
   "childrens": [],
}
```

And if you replay from someone username who already commented, it should be like this:

``` javascript
// REQUEST
POST: http://localhost:9000/input.php
From Data:
"parent_id": 2   // child comment    
"text": "in reply to someone"   // textarea input

// RESPONSE
{
   "success":true,
   "comment_id":7,
   "parent_id":2,      // child comment
   "text" : "in reply to someone",   // textarea input
   "in_reply_to":"username",
   "created_by":1,
   "posted_date":"2014-12-13 01:58:26",
   "childrens":[]
}
```

Thank you for asking and hope you get the idea.

**Comment by sivagopaltech** [comment]
Hi,
How to handle null response in get comments call.

**Comment by sivagopaltech** [comment]
Figured out the solution instead of returning empty array simply put return in server side.

**Comment by henyana** [comment]
Close the issue
